stages:
  - test
  - build

test_job:
  stage: test
  image: rust:latest
  before_script:
    - cd backend
    - rustc --version
    - cargo --version
    - cargo build --verbose --all
  script:
    - cargo test --verbose --all

build_backends:
  stage: build
  before_script:
    - cd backend
    - rustc --version
    - cargo --version
    - tree
  script:
    cargo build --verbose all --target x86_64-pc-windows-msvc -bin sh35-backend.exe
  artifacts:
    name: "prototype"
    untracked: false
    when: on_success
    paths:
      - "backend/target/release/sh35-backend.exe"
