[package]
name = "sh35-data-parsing"
version = "0.0.2"
edition = "2021"

[workspace]
members = [
    "src/geotiff",
]

[dependencies]
anyhow = "1.0.75"
rstar = "0.11.0"
xml-rs = "0.8.19"
proj = "0.27.2"
geotiff = { path="src/geotiff" }